<h1>02 - Tokens and Token Embeddings</h1>
<i>Exploring tokens and embeddings as an integral part of building LLMs</i>

In [1]:
# %%capture
# !pip install --upgrade transformers==4.41.2 sentence-transformers==3.0.1 gensim==4.3.2 scikit-learn==1.5.0 accelerate==0.31.0 peft==0.11.1 scipy==1.10.1 numpy==1.26.4

# Downloading and Running An LLM

The first step is to load our model onto the GPU for faster inference. Note that we load the model and tokenizer separately and keep them as such so that we can explore them separately.

In [2]:
import torch

In [3]:
from transformers import AutoModelForCausalLM, AutoTokenizer
model_path = "microsoft/Phi-3-mini-4k-instruct"
device = "mps" if torch.backends.mps.is_available() else "cpu"
# Load model and tokenizer
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map=device,
    torch_dtype="auto",
    trust_remote_code=False,
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [4]:
prompt = "Write an email apologizing to Sarah for the tragic gardening mishap. Explain how it happened.<|assistant|>"

In [5]:
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to('mps')
input_ids

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001]], device='mps:0')

In [6]:
device='mps'
# Tokenize the input prompt
encoded = tokenizer(prompt,padding=True, return_tensors="pt")

input_ids=encoded['input_ids'].to(device)
attention_mask=encoded['attention_mask'].to(device)
print(input_ids)
print(attention_mask)

# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  attention_mask=attention_mask,
  max_new_tokens=20
)

# # Print the output
# print(tokenizer.decode(generation_output[0]))

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001]], device='mps:0')
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
       device='mps:0')

You are not running the flash-attention implementation, expect numerical differences.

In [7]:
model.generate??

Signature:
model.generate(
    inputs: Optional[torch.Tensor] = None,
    generation_config: Optional[transformers.generation.configuration_utils.GenerationConfig] = None,
    logits_processor: Optional[transformers.generation.logits_process.LogitsProcessorList] = None,
    stopping_criteria: Optional[transformers.generation.stopping_criteria.StoppingCriteriaList] = None,
    prefix_allowed_tokens_fn: Optional[Callable[[int, torch.Tensor], List[int]]] = None,
    synced_gpus: Optional[bool] = None,
    assistant_model: Optional[ForwardRef('PreTrainedModel')] = None,
    streamer: Optional[ForwardRef('BaseStreamer')] = None,
    negative_prompt_ids: Optional[torch.Tensor] = None,
    negative_prompt_attention_mask: Optional[torch.Tensor] = None,
    **kwargs,
) -> Union[transformers.generation.utils.GenerateDecoderOnlyOutput, transformers.generation.utils.GenerateEncoderDecoderOutput, transformers.generation.utils.GenerateBeamDecoderOnlyOutput, transformers.generation.utils.GenerateBeamEncoderDecoderOutput, torch.LongTensor]
Source:
    @torch.no_grad()
    def generate(
        self,
        inputs: Optional[torch.Tensor] = None,
        generation_config: Optional[GenerationConfig] = None,
        logits_processor: Optional[LogitsProcessorList] = None,
        stopping_criteria: Optional[StoppingCriteriaList] = None,
        prefix_allowed_tokens_fn: Optional[Callable[[int, torch.Tensor], List[int]]] = None,
        synced_gpus: Optional[bool] = None,
        assistant_model: Optional["PreTrainedModel"] = None,
        streamer: Optional["BaseStreamer"] = None,
        negative_prompt_ids: Optional[torch.Tensor] = None,
        negative_prompt_attention_mask: Optional[torch.Tensor] = None,
        **kwargs,
    ) -> Union[GenerateOutput, torch.LongTensor]:
        r"""

        Generates sequences of token ids for models with a language modeling head.

        <Tip warning={true}>

        Most generation-controlling parameters are set in `generation_config` which, if not passed, will be set to the
        model's default generation configuration. You can override any `generation_config` by passing the corresponding
        parameters to generate(), e.g. `.generate(inputs, num_beams=4, do_sample=True)`.

        For an overview of generation strategies and code examples, check out the [following
        guide](../generation_strategies).

        </Tip>

        Parameters:
            inputs (`torch.Tensor` of varying shape depending on the modality, *optional*):
                The sequence used as a prompt for the generation or as model inputs to the encoder. If `None` the
                method initializes it with `bos_token_id` and a batch size of 1. For decoder-only models `inputs`
                should be in the format of `input_ids`. For encoder-decoder models *inputs* can represent any of
                `input_ids`, `input_values`, `input_features`, or `pixel_values`.
            generation_config ([`~generation.GenerationConfig`], *optional*):
                The generation configuration to be used as base parametrization for the generation call. `**kwargs`
                passed to generate matching the attributes of `generation_config` will override them. If
                `generation_config` is not provided, the default will be used, which has the following loading
                priority: 1) from the `generation_config.json` model file, if it exists; 2) from the model
                configuration. Please note that unspecified parameters will inherit [`~generation.GenerationConfig`]'s
                default values, whose documentation should be checked to parameterize generation.
            logits_processor (`LogitsProcessorList`, *optional*):
                Custom logits processors that complement the default logits processors built from arguments and
                generation config. If a logit processor is passed that is already created with the arguments or a
                generation config an error is thrown. This feature is intended for advanced users.
            stopping_criteria (`StoppingCriteriaList`, *optional*):
                Custom stopping criteria that complements the default stopping criteria built from arguments and a
                generation config. If a stopping criteria is passed that is already created with the arguments or a
                generation config an error is thrown. If your stopping criteria depends on the `scores` input, make
                sure you pass `return_dict_in_generate=True, output_scores=True` to `generate`. This feature is
                intended for advanced users.
            prefix_allowed_tokens_fn (`Callable[[int, torch.Tensor], List[int]]`, *optional*):
                If provided, this function constraints the beam search to allowed tokens only at each step. If not
                provided no constraint is applied. This function takes 2 arguments: the batch ID `batch_id` and
                `input_ids`. It has to return a list with the allowed tokens for the next generation step conditioned
                on the batch ID `batch_id` and the previously generated tokens `inputs_ids`. This argument is useful
                for constrained generation conditioned on the prefix, as described in [Autoregressive Entity
                Retrieval](https://arxiv.org/abs/2010.00904).
            synced_gpus (`bool`, *optional*):
                Whether to continue running the while loop until max_length. Unless overridden this flag will be set to
                `True` under DeepSpeed ZeRO Stage 3 multiple GPUs environment to avoid hanging if one GPU finished
                generating before other GPUs. Otherwise it'll be set to `False`.
            assistant_model (`PreTrainedModel`, *optional*):
                An assistant model that can be used to accelerate generation. The assistant model must have the exact
                same tokenizer. The acceleration is achieved when forecasting candidate tokens with the assistent model
                is much faster than running generation with the model you're calling generate from. As such, the
                assistant model should be much smaller.
            streamer (`BaseStreamer`, *optional*):
                Streamer object that will be used to stream the generated sequences. Generated tokens are passed
                through `streamer.put(token_ids)` and the streamer is responsible for any further processing.
            negative_prompt_ids (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                The negative prompt needed for some processors such as CFG. The batch size must match the input batch
                size. This is an experimental feature, subject to breaking API changes in future versions.
            negative_prompt_attention_mask (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
                Attention_mask for `negative_prompt_ids`.
            kwargs (`Dict[str, Any]`, *optional*):
                Ad hoc parametrization of `generation_config` and/or additional model-specific kwargs that will be
                forwarded to the `forward` function of the model. If the model is an encoder-decoder model, encoder
                specific kwargs should not be prefixed and decoder specific kwargs should be prefixed with *decoder_*.

        Return:
            [`~utils.ModelOutput`] or `torch.LongTensor`: A [`~utils.ModelOutput`] (if `return_dict_in_generate=True`
            or when `config.return_dict_in_generate=True`) or a `torch.LongTensor`.

                If the model is *not* an encoder-decoder model (`model.config.is_encoder_decoder=False`), the possible
                [`~utils.ModelOutput`] types are:

                    - [`~generation.GenerateDecoderOnlyOutput`],
                    - [`~generation.GenerateBeamDecoderOnlyOutput`]

                If the model is an encoder-decoder model (`model.config.is_encoder_decoder=True`), the possible
                [`~utils.ModelOutput`] types are:

                    - [`~generation.GenerateEncoderDecoderOutput`],
                    - [`~generation.GenerateBeamEncoderDecoderOutput`]
        """
        # 1. Handle `generation_config` and kwargs that might update it, and validate the `.generate()` call
        self._validate_model_class()
        tokenizer = kwargs.pop("tokenizer", None)  # Pull this out first, we only use it for stopping criteria
        generation_config, model_kwargs = self._prepare_generation_config(generation_config, **kwargs)
        self._validate_model_kwargs(model_kwargs.copy())

        # 2. Set generation parameters if not already defined
        if synced_gpus is None:
            if is_deepspeed_zero3_enabled() and dist.get_world_size() > 1:
                synced_gpus = True
            else:
                synced_gpus = False

        logits_processor = logits_processor if logits_processor is not None else LogitsProcessorList()
        stopping_criteria = stopping_criteria if stopping_criteria is not None else StoppingCriteriaList()

        accepts_attention_mask = "attention_mask" in set(inspect.signature(self.forward).parameters.keys())
        requires_attention_mask = "encoder_outputs" not in model_kwargs
        kwargs_has_attention_mask = model_kwargs.get("attention_mask", None) is not None

        # 3. Define model inputs
        inputs_tensor, model_input_name, model_kwargs = self._prepare_model_inputs(
            inputs, generation_config.bos_token_id, model_kwargs
        )
        batch_size = inputs_tensor.shape[0]

        device = inputs_tensor.device
        self._prepare_special_tokens(generation_config, kwargs_has_attention_mask, device=device)

        # decoder-only models must use left-padding for batched generation.
        if not self.config.is_encoder_decoder and not is_torchdynamo_compiling():
            # If `input_ids` was given, check if the last id in any sequence is `pad_token_id`
            # Note: If using, `inputs_embeds` this check does not work, because we want to be more hands-off.
            if (
                generation_config.pad_token_id is not None
                and batch_size > 1
                and len(inputs_tensor.shape) == 2
                and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
            ):
                logger.warning(
                    "A decoder-only architecture is being used, but right-padding was detected! For correct "
                    "generation results, please set `padding_side='left'` when initializing the tokenizer."
                )

        # 4. Define other model kwargs
        # decoder-only models with inputs_embeds forwarding must use caching (otherwise we can't detect whether we are
        # generating the first new token or not, and we only want to use the embeddings for the first new token)
        if not self.config.is_encoder_decoder and model_input_name == "inputs_embeds":
            model_kwargs["use_cache"] = True
        else:
            model_kwargs["use_cache"] = generation_config.use_cache

        if not kwargs_has_attention_mask and requires_attention_mask and accepts_attention_mask:
            model_kwargs["attention_mask"] = self._prepare_attention_mask_for_generation(
                inputs_tensor, generation_config.pad_token_id, generation_config.eos_token_id
            )

        if self.config.is_encoder_decoder and "encoder_outputs" not in model_kwargs:
            # if model is encoder decoder encoder_outputs are created and added to `model_kwargs`
            model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
                inputs_tensor, model_kwargs, model_input_name, generation_config
            )

        # 5. Prepare `input_ids` which will be used for auto-regressive generation
        if self.config.is_encoder_decoder:
            input_ids, model_kwargs = self._prepare_decoder_input_ids_for_generation(
                batch_size=batch_size,
                model_input_name=model_input_name,
                model_kwargs=model_kwargs,
                decoder_start_token_id=generation_config.decoder_start_token_id,
                device=inputs_tensor.device,
            )
        else:
            input_ids = inputs_tensor if model_input_name == "input_ids" else model_kwargs.pop("input_ids")

        if streamer is not None:
            streamer.put(input_ids.cpu())

        # 6. Prepare `max_length` depending on other stopping criteria.
        input_ids_length = input_ids.shape[-1]
        has_default_max_length = kwargs.get("max_length") is None and generation_config.max_length is not None
        has_default_min_length = kwargs.get("min_length") is None and generation_config.min_length is not None
        generation_config = self._prepare_generated_length(
            generation_config=generation_config,
            has_default_max_length=has_default_max_length,
            has_default_min_length=has_default_min_length,
            model_input_name=model_input_name,
            inputs_tensor=inputs_tensor,
            input_ids_length=input_ids_length,
        )

        if generation_config.cache_implementation is not None and model_kwargs.get("past_key_values") is not None:
            raise ValueError(
                "Passing both `cache_implementation` (used to initialize certain caches) and `past_key_values` (a "
                "Cache object) is unsupported. Please use only one of the two."
            )
        elif generation_config.cache_implementation in NEED_SETUP_CACHE_CLASSES_MAPPING:
            if not self._supports_cache_class:
                raise ValueError(
                    "This model does not support the `cache_implementation` argument. Please check the following "
                    "issue: https://github.com/huggingface/transformers/issues/28981."
                )
            if generation_config.cache_implementation == "static":
                if not self._supports_static_cache:
                    raise ValueError(
                        "This model does not support `cache_implementation='static'`. Please check the following "
                        "issue: https://github.com/huggingface/transformers/issues/28981"
                    )
                model_kwargs["past_key_values"] = self._get_static_cache(batch_size, generation_config.max_length)

        self._validate_generated_length(generation_config, input_ids_length, has_default_max_length)

        # 7. determine generation mode
        generation_mode = generation_config.get_generation_mode(assistant_model)

        if streamer is not None and (generation_config.num_beams > 1):
            raise ValueError(
                "`streamer` cannot be used with beam search (yet!). Make sure that `num_beams` is set to 1."
            )

        if self.device.type != input_ids.device.type:
            warnings.warn(
                "You are calling .generate() with the `input_ids` being on a device type different"
                f" than your model's device. `input_ids` is on {input_ids.device.type}, whereas the model"
                f" is on {self.device.type}. You may experience unexpected behaviors or slower generation."
                " Please make sure that you have put `input_ids` to the"
                f" correct device by calling for example input_ids = input_ids.to('{self.device.type}') before"
                " running `.generate()`.",
                UserWarning,
            )

        # 8. prepare distribution pre_processing samplers
        prepared_logits_processor = self._get_logits_processor(
            generation_config=generation_config,
            input_ids_seq_length=input_ids_length,
            encoder_input_ids=inputs_tensor,
            prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
            logits_processor=logits_processor,
            device=inputs_tensor.device,
            model_kwargs=model_kwargs,
            negative_prompt_ids=negative_prompt_ids,
            negative_prompt_attention_mask=negative_prompt_attention_mask,
        )

        # 9. prepare stopping criteria
        prepared_stopping_criteria = self._get_stopping_criteria(
            generation_config=generation_config, stopping_criteria=stopping_criteria, tokenizer=tokenizer, **kwargs
        )

        # 10. go into different generation modes
        if generation_mode == GenerationMode.ASSISTED_GENERATION:
            if generation_config.num_return_sequences > 1:
                raise ValueError(
                    "num_return_sequences has to be 1 when doing assisted generate, "
                    f"but is {generation_config.num_return_sequences}."
                )
            if batch_size > 1:
                raise ValueError("assisted generate is only supported for batch_size = 1")
            if not model_kwargs["use_cache"]:
                raise ValueError("assisted generate requires `use_cache=True`")
            if generation_config.cache_implementation == "static":
                raise ValueError("assisted generate is not supported with `static_cache`")

            # 11. Get the candidate generator, given the parameterization
            candidate_generator = self._get_candidate_generator(
                generation_config=generation_config,
                input_ids=input_ids,
                inputs_tensor=inputs_tensor,
                assistant_model=assistant_model,
                logits_processor=logits_processor,
                model_kwargs=model_kwargs,
            )

            # 12. prepare logits warper (if `do_sample` is `True`)
            prepared_logits_warper = (
                self._get_logits_warper(generation_config) if generation_config.do_sample else None
            )

            # 13. run assisted generate
            result = self._assisted_decoding(
                input_ids,
                candidate_generator=candidate_generator,
                logits_processor=prepared_logits_processor,
                logits_warper=prepared_logits_warper,
                stopping_criteria=prepared_stopping_criteria,
                generation_config=generation_config,
                synced_gpus=synced_gpus,
                streamer=streamer,
                **model_kwargs,
            )

        elif generation_mode == GenerationMode.CONTRASTIVE_SEARCH:
            if not model_kwargs["use_cache"]:
                raise ValueError("Contrastive search requires `use_cache=True`")

            result = self._contrastive_search(
                input_ids,
                logits_processor=prepared_logits_processor,
                stopping_criteria=prepared_stopping_criteria,
                generation_config=generation_config,
                synced_gpus=synced_gpus,
                streamer=streamer,
                **model_kwargs,
            )

        elif generation_mode in (GenerationMode.SAMPLE, GenerationMode.GREEDY_SEARCH):
            # 11. prepare logits warper
            prepared_logits_warper = (
                self._get_logits_warper(generation_config) if generation_config.do_sample else None
            )

            # 12. expand input_ids with `num_return_sequences` additional sequences per batch
            input_ids, model_kwargs = self._expand_inputs_for_generation(
                input_ids=input_ids,
                expand_size=generation_config.num_return_sequences,
                is_encoder_decoder=self.config.is_encoder_decoder,
                **model_kwargs,
            )

            # 13. run sample (it degenerates to greedy search when `generation_config.do_sample=False`)
            result = self._sample(
                input_ids,
                logits_processor=prepared_logits_processor,
                logits_warper=prepared_logits_warper,
                stopping_criteria=prepared_stopping_criteria,
                generation_config=generation_config,

In [8]:
for id in input_ids[0]:
   print(f'id is:{id},\t,decoded_id:{tokenizer.decode(id)}')

id is:14350,	,decoded_id:Write
id is:385,	,decoded_id:an
id is:4876,	,decoded_id:email
id is:27746,	,decoded_id:apolog
id is:5281,	,decoded_id:izing
id is:304,	,decoded_id:to
id is:19235,	,decoded_id:Sarah
id is:363,	,decoded_id:for
id is:278,	,decoded_id:the
id is:25305,	,decoded_id:trag
id is:293,	,decoded_id:ic
id is:16423,	,decoded_id:garden
id is:292,	,decoded_id:ing
id is:286,	,decoded_id:m
id is:728,	,decoded_id:ish
id is:481,	,decoded_id:ap
id is:29889,	,decoded_id:.
id is:12027,	,decoded_id:Exp
id is:7420,	,decoded_id:lain
id is:920,	,decoded_id:how
id is:372,	,decoded_id:it
id is:9559,	,decoded_id:happened
id is:29889,	,decoded_id:.
id is:32001,	,decoded_id:<|assistant|>

In [9]:
generation_output

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292,   286,   728,   481, 29889, 12027,  7420,   920,
           372,  9559, 29889, 32001,  3323,   622, 29901,   317,  3742,   406,
          6225, 11763,   363,   278, 19906,   292,   341,   728,   481,    13,
            13,    13, 29928,   799]], device='mps:0')

In [10]:
print(tokenizer.decode(3323))
print(tokenizer.decode(622))
print(tokenizer.decode([3323, 622]))
print(tokenizer.decode(29901))

Sub
ject
Subject
:

# Comparing Trained LLM Tokenizers

In [11]:
from transformers import AutoModelForCausalLM, AutoTokenizer

In [12]:
background_colors=['41', '42', '43', '44', '45', '46']
def show_tokens(sentence, tokenizer_name):
    tokenizer=AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids=tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
       standard_ansi=f'\x1b[{background_colors[idx%len(background_colors)]}m'
       reset_ansi='\x1b[0m'
       print(standard_ansi+tokenizer.decode(t)+reset_ansi,end='')

In [13]:
import numpy as np

In [14]:
numbers=np.random.randint(0, 255, size=(6, 3))

In [15]:
for i in numbers:
    print(*i,end='')

234 36 21283 73 9542 34 21686 122 124125 138 90177 148 115

In [16]:
text = """
$ 😂
English and CAPITALIZATION
🎵 鸟
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600
"""

In [17]:
show_tokens(text, "bert-base-uncased")

'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 38aa2215-21b6-46a0-be74-cad9d92935bf)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: f6715f18-5b22-4576-9adc-8484164d5ed2)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json
Retrying in 2s [Retry 2/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 524d043f-579f-4884-b75d-089451961363)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json
Retrying in 4s [Retry 3/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 94116d99-d100-4542-b390-f4c8e4265551)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 4/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 5eea12ea-f43f-454e-bb17-1b984b3bbe29)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 5/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 64c2f644-fefc-4827-be4e-84c7f5d67edf)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json

[CLS]$[UNK]englishandcapital##ization[UNK][UNK]show_token##sfalsenoneeli##f==>=else:twotab##s:""threetab##s:""12.0*50=600[SEP]

In [18]:
show_tokens(text, "bert-base-cased")

'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: d171943e-8b9a-4a61-9629-7e584ef5f7e8)')' thrown while requesting HEAD https://huggingface.co/bert-base-cased/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 549adbe6-5316-4bb1-8555-48c1892f983a)')' thrown while requesting HEAD https://huggingface.co/bert-base-cased/resolve/main/tokenizer_config.json
Retrying in 2s [Retry 2/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 7c66b395-d65c-49a7-a385-756d921809a2)')' thrown while requesting HEAD https://huggingface.co/bert-base-cased/resolve/main/tokenizer_config.json
Retrying in 4s [Retry 3/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 799677bc-d28d-4af6-ab10-fc5a8757a2dd)')' thrown while requesting HEAD https://huggingface.co/bert-base-cased/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 4/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 86caccd1-329d-43e9-a67b-a2f70bebaf38)')' thrown while requesting HEAD https://huggingface.co/bert-base-cased/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 5/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 7a1af577-0426-42ed-8265-40bb87678d9b)')' thrown while requesting HEAD https://huggingface.co/bert-base-cased/resolve/main/tokenizer_config.json

[CLS]$[UNK]EnglishandCA##PI##TA##L##I##Z##AT##ION[UNK][UNK]show_token##sF##als##eNoneel##if==>=else:twota##bs:""Threeta##bs:""12.0*50=600[SEP]

In [19]:
show_tokens(text, "gpt2")

'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: c1000dfe-ee74-4797-93f3-ee0c79548fde)')' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: f92fc95a-bf41-4c14-bd5b-ade173476cb2)')' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json
Retrying in 2s [Retry 2/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: afc3c6cc-715f-49bc-bcad-c6b1cc2c62ec)')' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json
Retrying in 4s [Retry 3/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: d4e7a6b0-e13c-4cd6-b0b8-95ab19a2c670)')' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 4/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 8] nodename nor servname provided, or not known)"))'), '(Request ID: 12126313-7140-4540-b4c7-7e43c15f06fd)')' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 5/5].

$ ��
English and CAPITALIZATION
��� ���
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600

In [20]:
## added by myself
tokenizer=AutoTokenizer.from_pretrained('gpt2')
tokenizer.decode([8582,236,113])

'🎵'

In [21]:
show_tokens(text, "google/flan-t5-small")

$<unk>EnglishandCAPITALIZATION<unk><unk>show_tokensFalseNoneelif==>=else:twotabs:""Threetabs:""12.0*50=600</s>

In [22]:
# The official is `tiktoken` but this the same tokenizer on the HF platform
show_tokens(text, "Xenova/gpt-4")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

$ ��
English and CAPITALIZATION
��� ���
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600

In [23]:
# You need to request access before being able to use this tokenizer
show_tokens(text, "bigcode/starcoder2-15b")

$ ��
English and CAPITALIZATION
��� ��
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600

In [24]:
show_tokens(text, "facebook/galactica-1.3b")

$ ����
English and CAPITALIZATION
���� ���
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600

In [25]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

$����
EnglishandCAPITALIZATION
�������
show_tokensFalseNoneelif==>=else:twotabs:"  "Threetabs:"     "
12.0*50=600

# Contextualized Word Embeddings From a Language Model (Like BERT)

In [26]:
from transformers import AutoModel, AutoTokenizer

# Load a tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

# Load a language model
model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

# Tokenize the sentence
tokens = tokenizer('Hello world', return_tensors='pt')

# Process the tokens
# Passing only input_ids using [0]
output = model(**tokens)[0]

In [27]:
output??

Type:        Tensor
String form:
tensor([[[-3.4816,  0.0861, -0.1819,  ..., -0.0612, -0.3911,  0.3017],
         [ 0.1898,  0.3208, -0.2315,  ...,  0.3714,  0.2478,  0.8048],
         [ 0.2071,  0.5036, -0.0485,  ...,  1.2175, -0.2292,  0.8582],
         [-3.4278,  0.0645, -0.1427,  ...,  0.0658, -0.4367,  0.3834]]],
       grad_fn=<NativeLayerNormBackward0>)
Length:      1
File:        /opt/anaconda3/envs/thellmbook/lib/python3.11/site-packages/torch/__init__.py
Docstring:   <no docstring>

In [28]:
output.shape

torch.Size([1, 4, 384])

# <ONLY For TEST

In [29]:
def parameter_inspector(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

In [30]:
parameter_inspector(**tokens)

input_ids: tensor([[    1, 31414,   232,     2]])
token_type_ids: tensor([[0, 0, 0, 0]])
attention_mask: tensor([[1, 1, 1, 1]])

In [31]:
tokens

{'input_ids': tensor([[    1, 31414,   232,     2]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [32]:
w=tokens['input_ids'][0]
print(w)

tensor([    1, 31414,   232,     2])

In [33]:
import numpy as np

In [34]:
three_shape=np.random.randint(0, 255, size=(1,2,2))
three_shape

array([[[80, 98],
        [25, 37]]])

In [35]:
three_shape[0][1][1]

37

# ONLY For TEST >

In [36]:
type(output)

torch.Tensor

In [37]:
print(output)

tensor([[[-3.4816,  0.0861, -0.1819,  ..., -0.0612, -0.3911,  0.3017],
         [ 0.1898,  0.3208, -0.2315,  ...,  0.3714,  0.2478,  0.8048],
         [ 0.2071,  0.5036, -0.0485,  ...,  1.2175, -0.2292,  0.8582],
         [-3.4278,  0.0645, -0.1427,  ...,  0.0658, -0.4367,  0.3834]]],
       grad_fn=<NativeLayerNormBackward0>)

In [38]:
output.shape

torch.Size([1, 4, 384])

In [39]:
for token in tokens['input_ids'][0]:
    print(f'id is:{token} \t  equivalent:{tokenizer.decode(token)}')

id is:1 	  equivalent:[CLS]
id is:31414 	  equivalent:Hello
id is:232 	  equivalent: world
id is:2 	  equivalent:[SEP]

In [40]:
output

tensor([[[-3.4816,  0.0861, -0.1819,  ..., -0.0612, -0.3911,  0.3017],
         [ 0.1898,  0.3208, -0.2315,  ...,  0.3714,  0.2478,  0.8048],
         [ 0.2071,  0.5036, -0.0485,  ...,  1.2175, -0.2292,  0.8582],
         [-3.4278,  0.0645, -0.1427,  ...,  0.0658, -0.4367,  0.3834]]],
       grad_fn=<NativeLayerNormBackward0>)

# Text Embeddings (For Sentences and Whole Documents)

# This is the alternative and shorter method for above method

In [41]:
from sentence_transformers import SentenceTransformer

# Load model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Convert text to text embeddings
vector = model.encode("Best movie ever!")

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/opt/anaconda3/envs/thellmbook/lib/python3.11/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [42]:
print(vector)
print(type(vector))

[-2.02204157e-02  4.57697064e-02 -1.26636969e-02 -3.37990746e-03
 -2.54909531e-03 -3.31097841e-03 -4.58366945e-02  2.32390966e-02
 -3.12585458e-02 -3.15589085e-02 -2.19783448e-02  3.67820193e-03
  3.39106540e-03 -1.88130792e-02 -2.65821610e-02 -1.45892687e-02
  3.20066959e-02 -3.66491778e-03  1.75410379e-02  5.43209650e-02
 -3.96662094e-02  9.93637461e-03 -3.27205025e-02 -1.62910372e-02
  6.36529410e-03 -1.24459155e-02  1.04737058e-02  3.08674518e-02
  7.47453189e-03 -3.86319980e-02 -6.19924366e-02 -3.25308964e-02
 -1.40269026e-02  5.16586974e-02  1.69651707e-06 -1.74110086e-04
 -1.27880741e-03 -4.15053181e-02  5.00346022e-03  4.58600633e-02
 -2.85337642e-02  5.02370670e-02 -1.75183769e-02 -3.98821750e-04
  1.63311474e-02  5.89936338e-02 -2.21729912e-02 -4.00975049e-02
 -6.60440046e-03 -2.97632832e-02 -3.18221673e-02 -1.77945606e-02
 -1.54362870e-02 -3.44515033e-02  6.25759810e-02  2.34394567e-03
  3.44158337e-02 -8.25460255e-03  7.44929686e-02 -3.81285213e-02
 -6.80808797e-02 -4.23290282e-02 -1.83172151e-02 -2.44083498e-02
  1.99337937e-02 -2.06878111e-02  2.39973255e-02  3.49854454e-02
 -6.95871934e-02  4.31548208e-02  1.57101210e-02 -4.87713655e-03
  6.38265759e-02  2.81547680e-02  5.08512333e-02 -2.83363760e-02
 -4.60656621e-02  6.47140294e-02  6.61476105e-02 -2.46199071e-02
 -6.05491549e-02 -3.04246717e-03  6.28791824e-02  2.83486769e-02
  5.71174063e-02  6.52742013e-03 -6.45670341e-03  1.11733126e-02
  2.18259599e-02 -1.60585102e-02  3.98900779e-03 -2.04678043e-03
  3.96751752e-03  4.18877155e-02 -2.90660746e-02 -4.19957973e-02
  4.34482768e-02  4.26486060e-02  7.53289461e-03 -3.28948796e-02
 -8.28770176e-03  2.01881193e-02  1.37377912e-02  1.38778305e-02
  4.24899235e-02  2.69807577e-02 -1.83730833e-02 -3.71769853e-02
  3.31590436e-02  2.42859386e-02 -3.89446802e-02  2.28919880e-03
  5.35069145e-02  6.79783747e-02 -9.70003102e-03 -6.89615775e-03
  8.24519843e-02 -4.85098409e-03 -1.19632268e-02  1.12271933e-02
 -1.84042491e-02 -9.23730340e-03 -2.06848029e-02  2.53276862e-02
 -1.11306086e-02 -4.08680132e-03 -2.30704658e-02 -2.89186463e-02
  4.45920117e-02 -3.02660419e-03 -4.13768478e-02  5.19979484e-02
  4.95348452e-03 -6.28712103e-02  3.07494067e-02  4.33227457e-02
 -2.99513713e-02 -2.41310173e-03  3.73286791e-02 -4.21255874e-03
  3.35870385e-02 -4.57396507e-02 -7.57045448e-02 -1.43844454e-05
  3.77049036e-02  1.17524955e-02  6.80494541e-03 -2.76923552e-03
  2.55940426e-02 -4.55860533e-02  3.38432230e-02 -2.46408042e-02
 -1.58957914e-02 -9.64221358e-03 -1.74004864e-02  1.95757225e-02
 -1.72166973e-02 -4.00131978e-02  8.84151645e-03  5.63180074e-03
 -5.64632192e-02  4.18703780e-02  6.14107512e-02 -2.33447701e-02
 -6.02261610e-02  2.65607256e-02 -8.73996876e-03 -2.54318584e-02
 -5.78649677e-02 -1.63428090e-03 -3.57385613e-02  8.78338795e-03
 -1.86853521e-02 -2.27693841e-02 -1.64403040e-02  9.16437421e-04
 -2.75911903e-03 -2.11251508e-02  1.17957965e-02  6.54988363e-02
 -1.34429233e-02 -5.85034210e-03 -2.26886161e-02 -4.69196821e-03
 -6.56696875e-03 -5.58425626e-03 -2.37320922e-02  2.63372692e-03
  2.79200599e-02  1.75013393e-02  7.05148652e-02  2.04411894e-03
  3.96886095e-02 -7.11206626e-03 -5.53245656e-03 -1.76759139e-02
 -9.80816968e-03  4.24946891e-03  5.34050129e-02  7.13995472e-02
  1.45237474e-02  6.63725054e-03  1.84460189e-02 -3.81757170e-02
 -1.90554447e-02 -5.48273064e-02 -1.84071753e-02 -4.95260805e-02
 -4.00507525e-02  8.68841726e-03 -2.48502400e-02  4.53157462e-02
  2.03235466e-02 -3.21139321e-02  1.56295542e-02  3.62752192e-02
  6.59925118e-02  3.26601006e-02 -8.78327414e-02  9.44340378e-02
  2.16405895e-02 -8.00883397e-03 -5.13046701e-03  1.49670271e-02
 -9.38000996e-03 -1.62820276e-02 -8.78262974e-04 -2.41658259e-02
  7.28241354e-02  5.07000163e-02 -7.54108047e-03  2.89575849e-02
  6.94771558e-02 -3.20685916e-02  8.36072396e-03  2.72289347e-02
  4.86845560e-02  2.09292658e-02 -4.85201366e-03 -1.35733619e-01
  5.91989271e-02  3.52462716e-02 -3.54933762e-03  5.53834112e-03
 -7.42449379e-03 -1.85083952e-02 -2.47552544e-02  3.68198045e-02
  4.10624668e-02  4.83442843e-03 -5.03981672e-02 -7.56623223e-03
 -7.34616295e-02 -1.37477377e-02 -4.96550910e-02 -5.77377900e-02
  2.30375566e-02  1.72316283e-02 -1.10098189e-02 -5.00852754e-03
  3.73133384e-02 -1.22196637e-02  3.67945433e-02  3.23758163e-02
  3.03839110e-02  3.12438551e-02  1.34678679e-02  2.09658989e-03
  9.05987155e-03  3.20697986e-02  4.30423319e-02  1.61133800e-02
 -1.97640946e-03  4.51487191e-02 -2.61758268e-03 -2.10353471e-02
  1.23143634e-02  2.19331346e-02 -7.48108402e-02 -1.87374521e-02
  5.77953923e-03 -1.66843478e-02  3.49257961e-02  1.69625189e-02
 -1.29547529e-02  2.42918115e-02  1.33142341e-02 -6.13084808e-03
  1.24595137e-02 -6.53127208e-02 -1.60474293e-02 -4.14024182e-02
  3.02160401e-02  3.15759368e-02  2.17898600e-02  9.32294596e-03
 -6.24404401e-02 -2.23614369e-02 -5.48126549e-02 -7.60867074e-02
 -4.92595769e-02  3.03733163e-02 -1.11725065e-03 -2.49408390e-02
  4.89795431e-02 -2.57986356e-02 -4.59413566e-02 -8.69548041e-03
 -1.24729276e-02  2.25808304e-02 -2.81890854e-02  5.30083925e-02
 -8.50981176e-02 -1.57342758e-02 -2.83089280e-02  1.50961317e-02
 -3.79605731e-03 -6.45769238e-02  2.63364110e-02  3.87118496e-02
 -4.34805435e-04 -1.71438847e-02 -3.64410765e-02  2.42590960e-02
 -2.05201879e-02  1.98236443e-02  3.23042311e-02 -5.71229309e-03
  4.89670709e-02  1.66043043e-02 -3.73699050e-03 -3.16586159e-02
  5.87325916e-02 -3.70643139e-02 -9.46528558e-03  1.18760699e-02
 -5.57537973e-02 -2.59902775e-02 -7.00723082e-02  4.13720459e-02
  9.44956578e-03  8.65645241e-03 -2.11737882e-02 -3.13928314e-02
 -4.39830907e-02 -2.41709910e-02 -6.17116876e-02 -7.56191313e-02
 -2.43743174e-02  5.23750111e-02  9.59650613e-03  2.09737457e-02
 -5.92918973e-03  2.82212417e-03  2.52180416e-02 -5.18823322e-03
 -2.51272433e-02 -2.08314452e-02 -1.32330647e-02 -2.14498229e-02
  4.04746644e-03  2.10041348e-02  2.12091763e-04  4.75078821e-02
  6.97088689e-02 -1.95958111e-02 -5.54394834e-02  3.15217637e-02
  1.19435433e-02 -3.56129035e-02 -4.14416008e-03 -1.77254551e-03
 -6.62559494e-02  3.22466493e-02 -2.87152976e-02 -2.36792453e-02
 -1.68482400e-02 -1.88505854e-02 -1.20192468e-02  7.32037588e-05
  3.12584490e-02  4.72666754e-04 -6.26350380e-03 -3.22463214e-02
 -2.92952098e-02  2.90423092e-02 -1.47413202e-02  2.43108403e-02
 -1.26743009e-02  7.43110701e-02  6.77753016e-02 -6.38449239e-03
 -8.33849330e-03  5.84005471e-03  3.46759371e-02 -7.89600797e-03
 -9.79568716e-03 -3.47787403e-02 -5.03329635e-02 -6.80285413e-03
 -2.32671085e-03  1.63682804e-01  3.31019796e-02  7.22550005e-02
  6.55808374e-02 -4.43070079e-04  7.60615021e-02  3.29805166e-02
 -2.50527784e-02  4.97032097e-03 -7.36759557e-06  1.77383772e-03
 -4.73156758e-02  1.24155302e-02 -1.79417431e-02 -3.96826584e-03
 -1.64653584e-02 -4.98488061e-02 -4.93971072e-02 -1.77264046e-02
 -5.79477800e-03  5.12049124e-02  6.15338273e-02 -2.02965587e-02
  4.10276204e-02  7.97442440e-03  1.60992495e-03  2.73904181e-03
  2.56858803e-02  3.49121466e-02  3.48256566e-02  2.99327150e-02
 -2.05292553e-02 -3.16913538e-02 -4.00760164e-03 -6.82935789e-02
  2.53672395e-02  1.60931889e-02  3.90192587e-03 -1.00664131e-03
 -4.16302010e-02  2.39276402e-02  1.93549562e-02  8.67195800e-03
 -4.15938683e-02 -2.54745036e-02 -2.57343799e-02 -2.41257679e-02
  1.68336439e-03 -1.94082153e-03 -1.33333972e-03 -2.77865715e-02
  9.17962380e-03 -5.63236475e-02  6.82892427e-02  2.38570496e-02
  3.62706073e-02 -9.64242313e-03  2.39587091e-02  2.71281879e-02
  9.78971869e-02  3.71735692e-02  1.77357923e-02 -4.09086160e-02
  5.76262176e-02  4.53529842e-02 -7.39419414e-03 -1.50913447e-02
  1.35779027e-02 -3.29060629e-02 -2.47588083e-02 -1.26152218e-03
  6.75928313e-03 -1.91759691e-02 -6.33704709e-03 -7.85872340e-02
  2.50525307e-02 -9.13120285e-02  3.05410065e-02 -2.07533408e-02
 -6.91620680e-03 -1.69424783e-03  1.80584583e-02 -9.01440997e-03
  6.07968979e-02 -7.59931207e-02 -3.42037156e-02  2.36437600e-02
 -6.94916723e-03  1.95292644e-02 -6.66128518e-03 -4.78446670e-03
 -1.23866778e-02 -2.50968058e-02 -6.64266571e-02 -3.37183215e-02
  2.51410622e-02 -4.08468135e-02  6.33136258e-02 -1.46273216e-02
  1.37926079e-02  8.56984220e-03 -2.74824239e-02  8.24874416e-02
 -3.33505459e-02 -1.88082624e-02  1.64880864e-02  2.23316122e-02
 -2.33952478e-02 -1.54915294e-02  1.58764739e-02  1.32024689e-02
 -3.13520916e-02 -3.49490196e-02  4.14551049e-02  2.04285327e-02
 -4.56376411e-02 -6.66560754e-02 -1.16886673e-02  2.10028067e-02
  9.88321099e-03 -6.19186927e-03 -4.83619198e-02  2.68509369e-02
  1.07399859e-02 -1.21470401e-03  3.40227932e-02 -4.31506633e-04
  7.58250579e-02  1.72219370e-02 -1.55712096e-02  1.66776567e-03
  9.24157351e-02  1.51795633e-02 -4.27687168e-02  1.10518165e-01
  2.41131689e-02  2.22333497e-03  1.09922262e-02  1.45182796e-02
 -5.40817045e-02 -2.92326463e-03 -1.81705840e-02 -6.50136219e-03
  8.84762481e-02 -4.08634730e-02 -2.46939100e-02 -5.75014809e-03
 -3.22964676e-02 -2.96047106e-02  1.48763147e-05  6.85955305e-03
  1.28586348e-02 -8.72277096e-03 -1.48364948e-02 -7.02032557e-33
 -4.22566151e-03 -7.70923570e-02 -6.34925580e-03  1.88374110e-02
 -1.08135238e-01  6.80673122e-03  1.62729360e-02  1.74700022e-02
 -3.21586616e-02 -1.56161154e-03 -1.21566672e-02  1.36200562e-02
  2.77593620e-02 -9.20705032e-03 -4.14167084e-02 -2.56592836e-02
 -1.12560485e-02  4.94263358e-02 -2.78256182e-03  9.62427293e-04
  4.10978198e-02  2.60311328e-02  4.17773426e-02  1.70261897e-02
 -3.55316550e-02  3.93776149e-02 -8.13048631e-02  2.14782869e-03
  6.34984970e-02  3.19656990e-02  5.42129315e-02  2.19707945e-04
 -1.19869765e-02 -4.00769450e-02  6.91371486e-02 -2.37348545e-02
  1.84541959e-02  5.91238141e-02 -1.81721859e-02 -3.54840904e-02
 -7.07990527e-02 -3.47007290e-02  2.24279752e-03 -6.55507669e-02
 -3.94935012e-02  1.90425161e-02 -1.63912326e-02  4.02781591e-02
  3.14997020e-03  1.21332053e-02 -6.33519068e-02 -6.07374962e-03
 -1.06719742e-02 -9.25485045e-02 -1.00544095e-02 -3.12487241e-02
 -1.62010994e-02  1.15962680e-02 -7.22086728e-02  3.07976939e-02
 -4.02981602e-02 -4.38704714e-02  7.42041832e-03 -1.51422806e-02
 -9.55197122e-03  3.73821482e-02  5.66349179e-02 -8.54411349e-03
  4.58105962e-04 -3.60886455e-02 -6.04566410e-02 -4.95447917e-03
 -1.58476103e-02 -3.05458647e-03  4.35595438e-02 -3.49933878e-02
 -8.74718204e-02 -2.11461093e-02  4.69010472e-02  1.14763726e-03
 -9.70439613e-03  1.26247006e-02  3.87018025e-02  1.04797119e-02
  3.05910986e-02 -4.95135738e-03 -2.14421786e-02  1.85080804e-02
 -4.06456888e-02  9.62920603e-04 -7.90949985e-02 -1.98711678e-02
 -6.67674327e-03 -1.66492090e-02  2.22318452e-02 -6.31384328e-02
 -2.61657909e-02 -5.00155948e-02 -1.82533246e-02  2.92075314e-02
  8.58040452e-02 -1.85399670e-02 -2.01680139e-02  5.81668057e-02
  9.49719995e-02  8.68616998e-03 -1.10520348e-02 -2.13645082e-02
  1.17103690e-02 -1.38579328e-02  1.19232386e-02  2.64743604e-02
 -2.23848931e-02  1.22721030e-04 -3.45518552e-02  2.53635254e-02
  3.13297734e-02  4.28087413e-02  2.94206403e-02 -1.82315763e-02
  1.32387895e-02  3.09947617e-02 -9.06949043e-02  1.72532834e-02
 -1.94001198e-02  3.73058990e-02  2.29968205e-02 -7.08247498e-02
 -1.39049347e-02 -9.68943699e-04  1.17215971e-02 -7.10178763e-02
  2.51297081e-07 -1.39412927e-02  7.07549555e-03 -8.92849173e-03
  1.10410266e-02  1.87252611e-02  2.12268829e-02 -2.81214844e-02
  2.27614418e-02  3.69848683e-02 -5.49840135e-03 -4.84631732e-02
  7.79398978e-02 -1.73098240e-02  2.15901881e-02  2.86326837e-02
  4.03624820e-03  4.57128324e-02 -1.19320467e-01 -2.15146933e-02
  4.14268026e-04 -3.48099042e-03 -3.38214040e-02 -2.95486096e-02
  5.80028929e-02 -5.94563894e-02 -3.89758423e-02  8.25333036e-03
  1.70043092e-02 -7.95116089e-03 -7.65289040e-03 -5.41234249e-03
  1.79019272e-02  2.96021961e-02  6.20511770e-02 -4.05848077e-05
 -7.20463991e-02  4.25473340e-02  2.78940573e-02 -5.75262569e-02
  6.42127246e-02 -4.63280901e-02  2.45122593e-02 -3.43407542e-02
  2.65387520e-02 -2.71381177e-02  3.75326350e-02  1.25608305e-02
 -2.84879957e-03 -2.97331866e-02  1.33427884e-02  6.07454367e-02
  1.28927017e-02 -4.96662371e-02  4.94488627e-02  1.42553309e-02
  3.98472548e-02  5.44130802e-02  1.44855725e-02  1.88953374e-02
 -2.00763084e-02 -9.07159224e-03 -1.45999212e-02  5.59378602e-03
  2.16931384e-02 -3.94870304e-02 -3.72502618e-02 -2.90761646e-02
  1.47246050e-34  7.02328756e-02 -2.57434100e-02  7.10346848e-02
 -1.78425368e-02  1.64556503e-02  3.00991479e-02  5.60348947e-03
  9.69085284e-03  6.91118464e-02 -1.28523912e-02 -5.07156644e-03]
<class 'numpy.ndarray'>

In [43]:
vector.shape

(768,)

# Word Embeddings Beyond LLMs

In [44]:
import gensim.downloader as api

# Download embeddings (66MB, glove, trained on wikipedia, vector size: 50)
# Other options include "word2vec-google-news-300"
# More options at https://github.com/RaRe-Technologies/gensim-data
model = api.load("glove-wiki-gigaword-50")

In [45]:
api.info()

{'corpora': {'semeval-2016-2017-task3-subtaskBC': {'num_records': -1,
   'record_format': 'dict',
   'file_size': 6344358,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/semeval-2016-2017-task3-subtaskB-eng/__init__.py',
   'license': 'All files released for the task are free for general research use',
   'fields': {'2016-train': ['...'],
    '2016-dev': ['...'],
    '2017-test': ['...'],
    '2016-test': ['...']},
   'description': 'SemEval 2016 / 2017 Task 3 Subtask B and C datasets contain train+development (317 original questions, 3,169 related questions, and 31,690 comments), and test datasets in English. The description of the tasks and the collected data is given in sections 3 and 4.1 of the task paper http://alt.qcri.org/semeval2016/task3/data/uploads/semeval2016-task3-report.pdf linked in section “Papers” of https://github.com/RaRe-Technologies/gensim-data/issues/18.',
   'checksum': '701ea67acd82e75f95e1d8e62fb0ad29',
   'file_name': 'semeval-2016-2017-task3-subtaskBC.gz',
   'read_more': ['http://alt.qcri.org/semeval2017/task3/',
    'http://alt.qcri.org/semeval2017/task3/data/uploads/semeval2017-task3.pdf',
    'https://github.com/RaRe-Technologies/gensim-data/issues/18',
    'https://github.com/Witiko/semeval-2016_2017-task3-subtaskB-english'],
   'parts': 1},
  'semeval-2016-2017-task3-subtaskA-unannotated': {'num_records': 189941,
   'record_format': 'dict',
   'file_size': 234373151,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/semeval-2016-2017-task3-subtaskA-unannotated-eng/__init__.py',
   'license': 'These datasets are free for general research use.',
   'fields': {'THREAD_SEQUENCE': '',
    'RelQuestion': {'RELQ_CATEGORY': 'question category, according to the Qatar Living taxonomy',
     'RELQ_DATE': 'date of posting',
     'RELQ_ID': 'question indentifier',
     'RELQ_USERID': 'identifier of the user asking the question',
     'RELQ_USERNAME': 'name of the user asking the question',
     'RelQBody': 'body of question',
     'RelQSubject': 'subject of question'},
    'RelComments': [{'RelCText': 'text of answer',
      'RELC_USERID': 'identifier of the user posting the comment',
      'RELC_ID': 'comment identifier',
      'RELC_USERNAME': 'name of the user posting the comment',
      'RELC_DATE': 'date of posting'}]},
   'description': 'SemEval 2016 / 2017 Task 3 Subtask A unannotated dataset contains 189,941 questions and 1,894,456 comments in English collected from the Community Question Answering (CQA) web forum of Qatar Living. These can be used as a corpus for language modelling.',
   'checksum': '2de0e2f2c4f91c66ae4fcf58d50ba816',
   'file_name': 'semeval-2016-2017-task3-subtaskA-unannotated.gz',
   'read_more': ['http://alt.qcri.org/semeval2016/task3/',
    'http://alt.qcri.org/semeval2016/task3/data/uploads/semeval2016-task3-report.pdf',
    'https://github.com/RaRe-Technologies/gensim-data/issues/18',
    'https://github.com/Witiko/semeval-2016_2017-task3-subtaskA-unannotated-english'],
   'parts': 1},
  'patent-2017': {'num_records': 353197,
   'record_format': 'dict',
   'file_size': 3087262469,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/patent-2017/__init__.py',
   'license': 'not found',
   'description': "Patent Grant Full Text. Contains the full text including tables, sequence data and 'in-line' mathematical expressions of each patent grant issued in 2017.",
   'checksum-0': '818501f0b9af62d3b88294d86d509f8f',
   'checksum-1': '66c05635c1d3c7a19b4a335829d09ffa',
   'file_name': 'patent-2017.gz',
   'read_more': ['http://patents.reedtech.com/pgrbft.php'],
   'parts': 2},
  'quora-duplicate-questions': {'num_records': 404290,
   'record_format': 'dict',
   'file_size': 21684784,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/quora-duplicate-questions/__init__.py',
   'license': 'probably https://www.quora.com/about/tos',
   'fields': {'question1': 'the full text of each question',
    'question2': 'the full text of each question',
    'qid1': 'unique ids of each question',
    'qid2': 'unique ids of each question',
    'id': 'the id of a training set question pair',
    'is_duplicate': 'the target variable, set to 1 if question1 and question2 have essentially the same meaning, and 0 otherwise'},
   'description': 'Over 400,000 lines of potential question duplicate pairs. Each line contains IDs for each question in the pair, the full text for each question, and a binary value that indicates whether the line contains a duplicate pair or not.',
   'checksum': 'd7cfa7fbc6e2ec71ab74c495586c6365',
   'file_name': 'quora-duplicate-questions.gz',
   'read_more': ['https://data.quora.com/First-Quora-Dataset-Release-Question-Pairs'],
   'parts': 1},
  'wiki-english-20171001': {'num_records': 4924894,
   'record_format': 'dict',
   'file_size': 6516051717,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/wiki-english-20171001/__init__.py',
   'license': 'https://dumps.wikimedia.org/legal.html',
   'fields': {'section_texts': 'list of body of sections',
    'section_titles': 'list of titles of sections',
    'title': 'Title of wiki article'},
   'description': 'Extracted Wikipedia dump from October 2017. Produced by `python -m gensim.scripts.segment_wiki -f enwiki-20171001-pages-articles.xml.bz2 -o wiki-en.gz`',
   'checksum-0': 'a7d7d7fd41ea7e2d7fa32ec1bb640d71',
   'checksum-1': 'b2683e3356ffbca3b6c2dca6e9801f9f',
   'checksum-2': 'c5cde2a9ae77b3c4ebce804f6df542c2',
   'checksum-3': '00b71144ed5e3aeeb885de84f7452b81',
   'file_name': 'wiki-english-20171001.gz',
   'read_more': ['https://dumps.wikimedia.org/enwiki/20171001/'],
   'parts': 4},
  'text8': {'num_records': 1701,
   'record_format': 'list of str (tokens)',
   'file_size': 33182058,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/text8/__init__.py',
   'license': 'not found',
   'description': 'First 100,000,000 bytes of plain text from Wikipedia. Used for testing purposes; see wiki-english-* for proper full Wikipedia datasets.',
   'checksum': '68799af40b6bda07dfa47a32612e5364',
   'file_name': 'text8.gz',
   'read_more': ['http://mattmahoney.net/dc/textdata.html'],
   'parts': 1},
  'fake-news': {'num_records': 12999,
   'record_format': 'dict',
   'file_size': 20102776,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/fake-news/__init__.py',
   'license': 'https://creativecommons.org/publicdomain/zero/1.0/',
   'fields': {'crawled': 'date the story was archived',
    'ord_in_thread': '',
    'published': 'date published',
    'participants_count': 'number of participants',
    'shares': 'number of Facebook shares',
    'replies_count': 'number of replies',
    'main_img_url': 'image from story',
    'spam_score': 'data from webhose.io',
    'uuid': 'unique identifier',
    'language': 'data from webhose.io',
    'title': 'title of story',
    'country': 'data from webhose.io',
    'domain_rank': 'data from webhose.io',
    'author': 'author of story',
    'comments': 'number of Facebook comments',
    'site_url': 'site URL from BS detector',
    'text': 'text of story',
    'thread_title': '',
    'type': 'type of website (label from BS detector)',
    'likes': 'number of Facebook likes'},
   'description': "News dataset, contains text and metadata from 244 websites and represents 12,999 posts in total from a specific window of 30 days. The data was pulled using the webhose.io API, and because it's coming from their crawler, not all websites identified by their BS Detector are present in this dataset. Data sources that were missing a label were simply assigned a label of 'bs'. There are (ostensibly) no genuine, reliable, or trustworthy news sources represented in this dataset (so far), so don't trust anything you read.",
   'checksum': '5e64e942df13219465927f92dcefd5fe',
   'file_name': 'fake-news.gz',
   'read_more': ['https://www.kaggle.com/mrisdal/fake-news'],
   'parts': 1},
  '20-newsgroups': {'num_records': 18846,
   'record_format': 'dict',
   'file_size': 14483581,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/20-newsgroups/__init__.py',
   'license': 'not found',
   'fields': {'topic': 'name of topic (20 variant of possible values)',
    'set': "marker of original split (possible values 'train' and 'test')",
    'data': '',
    'id': 'original id inferred from folder name'},
   'description': 'The notorious collection of approximately 20,000 newsgroup posts, partitioned (nearly) evenly across 20 different newsgroups.',
   'checksum': 'c92fd4f6640a86d5ba89eaad818a9891',
   'file_name': '20-newsgroups.gz',
   'read_more': ['http://qwone.com/~jason/20Newsgroups/'],
   'parts': 1},
  '__testing_matrix-synopsis': {'description': '[THIS IS ONLY FOR TESTING] Synopsis of the movie matrix.',
   'checksum': '1767ac93a089b43899d54944b07d9dc5',
   'file_name': '__testing_matrix-synopsis.gz',
   'read_more': ['http://www.imdb.com/title/tt0133093/plotsummary?ref_=ttpl_pl_syn#synopsis'],
   'parts': 1},
  '__testing_multipart-matrix-synopsis': {'description': '[THIS IS ONLY FOR TESTING] Synopsis of the movie matrix.',
   'checksum-0': 'c8b0c7d8cf562b1b632c262a173ac338',
   'checksum-1': '5ff7fc6818e9a5d9bc1cf12c35ed8b96',
   'checksum-2': '966db9d274d125beaac7987202076cba',
   'file_name': '__testing_multipart-matrix-synopsis.gz',
   'read_more': ['http://www.imdb.com/title/tt0133093/plotsummary?ref_=ttpl_pl_syn#synopsis'],
   'parts': 3}},
 'models': {'fasttext-wiki-news-subwords-300': {'num_records': 999999,
   'file_size': 1005007116,
   'base_dataset': 'Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset (16B tokens)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/fasttext-wiki-news-subwords-300/__init__.py',
   'license': 'https://creativecommons.org/licenses/by-sa/3.0/',
   'parameters': {'dimension': 300},
   'description': '1 million word vectors trained on Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset (16B tokens).',
   'read_more': ['https://fasttext.cc/docs/en/english-vectors.html',
    'https://arxiv.org/abs/1712.09405',
    'https://arxiv.org/abs/1607.01759'],
   'checksum': 'de2bb3a20c46ce65c9c131e1ad9a77af',
   'file_name': 'fasttext-wiki-news-subwords-300.gz',
   'parts': 1},
  'conceptnet-numberbatch-17-06-300': {'num_records': 1917247,
   'file_size': 1225497562,
   'base_dataset': 'ConceptNet, word2vec, GloVe, and OpenSubtitles 2016',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/conceptnet-numberbatch-17-06-300/__init__.py',
   'license': 'https://github.com/commonsense/conceptnet-numberbatch/blob/master/LICENSE.txt',
   'parameters': {'dimension': 300},
   'description': 'ConceptNet Numberbatch consists of state-of-the-art semantic vectors (also known as word embeddings) that can be used directly as a representation of word meanings or as a starting point for further machine learning. ConceptNet Numberbatch is part of the ConceptNet open data project. ConceptNet provides lots of ways to compute with word meanings, one of which is word embeddings. ConceptNet Numberbatch is a snapshot of just the word embeddings. It is built using an ensemble that combines data from ConceptNet, word2vec, GloVe, and OpenSubtitles 2016, using a variation on retrofitting.',
   'read_more': ['http://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14972',
    'https://github.com/commonsense/conceptnet-numberbatch',
    'http://conceptnet.io/'],
   'checksum': 'fd642d457adcd0ea94da0cd21b150847',
   'file_name': 'conceptnet-numberbatch-17-06-300.gz',
   'parts': 1},
  'word2vec-ruscorpora-300': {'num_records': 184973,
   'file_size': 208427381,
   'base_dataset': 'Russian National Corpus (about 250M words)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/word2vec-ruscorpora-300/__init__.py',
   'license': 'https://creativecommons.org/licenses/by/4.0/deed.en',
   'parameters': {'dimension': 300, 'window_size': 10},
   'description': 'Word2vec Continuous Skipgram vectors trained on full Russian National Corpus (about 250M words). The model contains 185K words.',
   'preprocessing': 'The corpus was lemmatized and tagged with Universal PoS',
   'read_more': ['https://www.academia.edu/24306935/WebVectors_a_Toolkit_for_Building_Web_Interfaces_for_Vector_Semantic_Models',
    'http://rusvectores.org/en/',
    'https://github.com/RaRe-Technologies/gensim-data/issues/3'],
   'checksum': '9bdebdc8ae6d17d20839dd9b5af10bc4',
   'file_name': 'word2vec-ruscorpora-300.gz',
   'parts': 1},
  'word2vec-google-news-300': {'num_records': 3000000,
   'file_size': 1743563840,
   'base_dataset': 'Google News (about 100 billion words)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/word2vec-google-news-300/__init__.py',
   'license': 'not found',
   'parameters': {'dimension': 300},
   'description': "Pre-trained vectors trained on a part of the Google News dataset (about 100 billion words). The model contains 300-dimensional vectors for 3 million words and phrases. The phrases were obtained using a simple data-driven approach described in 'Distributed Representations of Words and Phrases and their Compositionality' (https://code.google.com/archive/p/word2vec/).",
   'read_more': ['https://code.google.com/archive/p/word2vec/',
    'https://arxiv.org/abs/1301.3781',
    'https://arxiv.org/abs/1310.4546',
    'https://www.microsoft.com/en-us/research/publication/linguistic-regularities-in-continuous-space-word-representations/?from=http%3A%2F%2Fresearch.microsoft.com%2Fpubs%2F189726%2Frvecs.pdf'],
   'checksum': 'a5e5354d40acb95f9ec66d5977d140ef',
   'file_name': 'word2vec-google-news-300.gz',
   'parts': 1},
  'glove-wiki-gigaword-50': {'num_records': 400000,
   'file_size': 69182535,
   'base_dataset': 'Wikipedia 2014 + Gigaword 5 (6B tokens, uncased)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-wiki-gigaword-50/__init__.py',
   'license': 'http://opendatacommons.org/licenses/pddl/',
   'parameters': {'dimension': 50},
   'description': 'Pre-trained vectors based on Wikipedia 2014 + Gigaword, 5.6B tokens, 400K vocab, uncased (https://nlp.stanford.edu/projects/glove/).',
   'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-wiki-gigaword-50.txt`.',
   'read_more': ['https://nlp.stanford.edu/projects/glove/',
    'https://nlp.stanford.edu/pubs/glove.pdf'],
   'checksum': 'c289bc5d7f2f02c6dc9f2f9b67641813',
   'file_name': 'glove-wiki-gigaword-50.gz',
   'parts': 1},
  'glove-wiki-gigaword-100': {'num_records': 400000,
   'file_size': 134300434,
   'base_dataset': 'Wikipedia 2014 + Gigaword 5 (6B tokens, uncased)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-wiki-gigaword-100/__init__.py',
   'license': 'http://opendatacommons.org/licenses/pddl/',
   'parameters': {'dimension': 100},
   'description': 'Pre-trained vectors based on Wikipedia 2014 + Gigaword 5.6B tokens, 400K vocab, uncased (https://nlp.stanford.edu/projects/glove/).',
   'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-wiki-gigaword-100.txt`.',
   'read_more': ['https://nlp.stanford.edu/projects/glove/',
    'https://nlp.stanford.edu/pubs/glove.pdf'],
   'checksum': '40ec481866001177b8cd4cb0df92924f',
   'file_name': 'glove-wiki-gigaword-100.gz',
   'parts': 1},
  'glove-wiki-gigaword-200': {'num_records': 400000,
   'file_size': 264336934,
   'base_dataset': 'Wikipedia 2014 + Gigaword 5 (6B tokens, uncased)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-wiki-gigaword-200/__init__.py',
   'license': 'http://opendatacommons.org/licenses/pddl/',
   'parameters': {'dimension': 200},
   'description': 'Pre-trained vectors based on Wikipedia 2014 + Gigaword, 5.6B tokens, 400K vocab, uncased (https://nlp.stanford.edu/projects/glove/).',
   'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-wiki-gigaword-200.txt`.',
   'read_more': ['https://nlp.stanford.edu/projects/glove/',
    'https://nlp.stanford.edu/pubs/glove.pdf'],
   'checksum': '59652db361b7a87ee73834a6c391dfc1',
   'file_name': 'glove-wiki-gigaword-200.gz',
   'parts': 1},
  'glove-wiki-gigaword-300': {'num_records': 400000,
   'file_size': 394362229,
   'base_dataset': 'Wikipedia 2014 + Gigaword 5 (6B tokens, uncased)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-wiki-gigaword-300/__init__.py',
   'license': 'http://opendatacommons.org/licenses/pddl/',
   'parameters': {'dimension': 300},
   'description': 'Pre-trained vectors based on Wikipedia 2014 + Gigaword, 5.6B tokens, 400K vocab, uncased (https://nlp.stanford.edu/projects/glove/).',
   'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-wiki-gigaword-300.txt`.',
   'read_more': ['https://nlp.stanford.edu/projects/glove/',
    'https://nlp.stanford.edu/pubs/glove.pdf'],
   'checksum': '29e9329ac2241937d55b852e8284e89b',
   'file_name': 'glove-wiki-gigaword-300.gz',
   'parts': 1},
  'glove-twitter-25': {'num_records': 1193514,
   'file_size': 109885004,
   'base_dataset': 'Twitter (2B tweets, 27B tokens, 1.2M vocab, uncased)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-twitter-25/__init__.py',
   'license': 'http://opendatacommons.org/licenses/pddl/',
   'parameters': {'dimension': 25},
   'description': 'Pre-trained vectors based on 2B tweets, 27B tokens, 1.2M vocab, uncased (https://nlp.stanford.edu/projects/glove/).',
   'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-twitter-25.txt`.',
   'read_more': ['https://nlp.stanford.edu/projects/glove/',
    'https://nlp.stanford.edu/pubs/glove.pdf'],
   'checksum': '50db0211d7e7a2dcd362c6b774762793',
   'file_name': 'glove-twitter-25.gz',
   'parts': 1},
  'glove-twitter-50': {'num_records': 1193514,
   'file_size': 209216938,
   'base_dataset': 'Twitter (2B tweets, 27B tokens, 1.2M vocab, uncased)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-twitter-50/__init__.py',
   'license': 'http://opendatacommons.org/licenses/pddl/',
   'parameters': {'dimension': 50},
   'description': 'Pre-trained vectors based on 2B tweets, 27B tokens, 1.2M vocab, uncased (https://nlp.stanford.edu/projects/glove/)',
   'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-twitter-50.txt`.',
   'read_more': ['https://nlp.stanford.edu/projects/glove/',
    'https://nlp.stanford.edu/pubs/glove.pdf'],
   'checksum': 'c168f18641f8c8a00fe30984c4799b2b',
   'file_name': 'glove-twitter-50.gz',
   'parts': 1},
  'glove-twitter-100': {'num_records': 1193514,
   'file_size': 405932991,
   'base_dataset': 'Twitter (2B tweets, 27B tokens, 1.2M vocab, uncased)',
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-twitter-100/__init__.py',
   'license': 'http://opendatacommons.org/licenses/pddl/',
   'parameters': {'dimension': 100},
   'description': 'Pre-trained vectors based on  2B tweets, 27B tokens, 1.2M vocab, uncased (https://nlp.stanford.edu/projects/glove/)',
   'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-twitter-100.txt`.',
   'read_more': ['https://nlp.stanford.edu/projects/glove/',
    'https://nlp.stanford.edu/pubs/glove.pdf'],
   'checksum': 'b04f7bed38756d64cf55b58ce7e97b15',
   'file_name': 'glove-twitter-100.gz',
   'parts': 1},

In [46]:
model.most_similar([model['king']], topn=11)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839044332504272),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542160749435425),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492412328720093),
 ('ruler', 0.7434254288673401)]

In [47]:
model.most_similar??

Signature:
model.most_similar(
    positive=None,
    negative=None,
    topn=10,
    clip_start=0,
    clip_end=None,
    restrict_vocab=None,
    indexer=None,
)
Source:
    def most_similar(
            self, positive=None, negative=None, topn=10, clip_start=0, clip_end=None,
            restrict_vocab=None, indexer=None,
        ):
        """Find the top-N most similar keys.
        Positive keys contribute positively towards the similarity, negative keys negatively.

        This method computes cosine similarity between a simple mean of the projection
        weight vectors of the given keys and the vectors for each key in the model.
        The method corresponds to the `word-analogy` and `distance` scripts in the original
        word2vec implementation.

        Parameters
        ----------
        positive : list of (str or int or ndarray) or list of ((str,float) or (int,float) or (ndarray,float)), optional
            List of keys that contribute positively. If tuple, second element specifies the weight (default `1.0`)
        negative : list of (str or int or ndarray) or list of ((str,float) or (int,float) or (ndarray,float)), optional
            List of keys that contribute negatively. If tuple, second element specifies the weight (default `-1.0`)
        topn : int or None, optional
            Number of top-N similar keys to return, when `topn` is int. When `topn` is None,
            then similarities for all keys are returned.
        clip_start : int
            Start clipping index.
        clip_end : int
            End clipping index.
        restrict_vocab : int, optional
            Optional integer which limits the range of vectors which
            are searched for most-similar values. For example, restrict_vocab=10000 would
            only check the first 10000 key vectors in the vocabulary order. (This may be
            meaningful if you've sorted the vocabulary by descending frequency.) If
            specified, overrides any values of ``clip_start`` or ``clip_end``.

        Returns
        -------
        list of (str, float) or numpy.array
            When `topn` is int, a sequence of (key, similarity) is returned.
            When `topn` is None, then similarities for all keys are returned as a
            one-dimensional numpy array with the size of the vocabulary.

        """
        if isinstance(topn, Integral) and topn < 1:
            return []

        # allow passing a single string-key or vector for the positive/negative arguments
        positive = _ensure_list(positive)
        negative = _ensure_list(negative)

        self.fill_norms()
        clip_end = clip_end or len(self.vectors)

        if restrict_vocab:
            clip_start = 0
            clip_end = restrict_vocab

        # add weights for each key, if not already present; default to 1.0 for positive and -1.0 for negative keys
        keys = []
        weight = np.concatenate((np.ones(len(positive)), -1.0 * np.ones(len(negative))))
        for idx, item in enumerate(positive + negative):
            if isinstance(item, _EXTENDED_KEY_TYPES):
                keys.append(item)
            else:
                keys.append(item[0])
                weight[idx] = item[1]

        # compute the weighted average of all keys
        mean = self.get_mean_vector(keys, weight, pre_normalize=True, post_normalize=True, ignore_missing=False)
        all_keys = [
            self.get_index(key) for key in keys if isinstance(key, _KEY_TYPES) and self.has_index_for(key)
        ]

        if indexer is not None and isinstance(topn, int):
            return indexer.most_similar(mean, topn)

        dists = dot(self.vectors[clip_start:clip_end], mean) / self.norms[clip_start:clip_end]
        if not topn:
            return dists
        best = matutils.argsort(dists, topn=topn + len(all_keys), reverse=True)
        # ignore (don't return) keys from the input
        result = [
            (self.index_to_key[sim + clip_start], float(dists[sim]))
            for sim in best if (sim + clip_start) not in all_keys
        ]
        return result[:topn]
File:      /opt/anaconda3/envs/thellmbook/lib/python3.11/site-packages/gensim/models/keyedvectors.py
Type:      method

In [48]:
model.most_similar([model['bridge']],topn=60)

[('bridge', 0.9999998807907104),
 ('road', 0.8527507185935974),
 ('bridges', 0.8246731758117676),
 ('tunnel', 0.8163517713546753),
 ('connecting', 0.7905849814414978),
 ('crosses', 0.7779373526573181),
 ('along', 0.7731157541275024),
 ('railway', 0.7710516452789307),
 ('crossing', 0.7682911157608032),
 ('rail', 0.761237382888794),
 ('highway', 0.7581579089164734),
 ('gate', 0.7550985217094421),
 ('canal', 0.7430083155632019),
 ('route', 0.7392379641532898),
 ('lane', 0.735925555229187),
 ('viaduct', 0.7353712916374207),
 ('constructed', 0.7335984110832214),
 ('embankment', 0.7333869338035583),
 ('built', 0.7328950762748718),
 ('roadway', 0.731002926826477),
 ('river', 0.7267074584960938),
 ('east', 0.7251012921333313),
 ('roads', 0.7232987880706787),
 ('junction', 0.7231907844543457),
 ('railroad', 0.722453773021698),
 ('parkway', 0.7220357656478882),
 ('adjacent', 0.7217997908592224),
 ('entrance', 0.7199317216873169),
 ('line', 0.7192555069923401),
 ('connects', 0.7173622250556946),
 ('tower', 0.7152627110481262),
 ('freeway', 0.708511233329773),
 ('west', 0.7077879309654236),
 ('north', 0.7026620507240295),
 ('terminus', 0.7008851766586304),
 ('footbridge', 0.700263500213623),
 ('expressway', 0.6994278430938721),
 ('corridor', 0.6951942443847656),
 ('located', 0.6939460635185242),
 ('main', 0.6897904872894287),
 ('near', 0.6897875070571899),
 ('building', 0.6879069209098816),
 ('overpass', 0.6870704293251038),
 ('shore', 0.6862057447433472),
 ('walkway', 0.6836602091789246),
 ('interchange', 0.6799198389053345),
 ('section', 0.6767610311508179),
 ('tunnels', 0.6757010817527771),
 ('paved', 0.675290584564209),
 ('winding', 0.6737698912620544),
 ('fence', 0.6734440922737122),
 ('construction', 0.673235297203064),
 ('avenue', 0.6708758473396301),
 ('park', 0.6703193187713623),
 ('historic', 0.6686797142028809),
 ('lines', 0.6676428914070129),
 ('dam', 0.667630136013031),
 ('intersection', 0.667597770690918),
 ('situated', 0.6648961901664734),
 ('through', 0.6630593538284302)]

# Recommending songs by embeddings

In [88]:
import pandas as pd
from urllib import request

In [89]:
# Get the playlist dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

In [90]:
# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

In [91]:
# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [103]:
songs_df.head(10)

                                                title       artist
id
0                        Gucci Time (w\/ Swizz Beatz)   Gucci Mane
1   Aston Martin Music (w\/ Drake & Chrisette Mich...    Rick Ross
2                       Get Back Up (w\/ Chris Brown)         T.I.
3                  Hot Toddy (w\/ Jay-Z & Ester Dean)        Usher
4                                        Whip My Hair       Willow
5                            Down On Me (w\/ 50 Cent)      Jeremih
6                                    Black And Yellow  Wiz Khalifa
7                                   Blowing Me Kisses   Soulja Boy
8                                         Lay It Down        Lloyd
9                       Good For My Money (w\/ Lloyd)    Baby Bash

In [92]:
print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

Playlist #1:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43']

Playlist #2:
  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117', '118', '119', '120', '121', '122', '123', '50', '70', '71', '124', '17', '85', '14', '82', '48', '125', '47', '46', '72', '53', '25', '73', '4', '126', '59', '74', '20', '43', '127', '128', '129', '13', '82', '48', '130', '131', '132', '133', '134', '135', '136', '137', '59', '46', '138', '43', '20', '139', '140', '73', '57', '70', '141', '3', '1', '74', '142', '143', '144', '145', '48', '13', '25', '146', '50', '147', '126', '59', '20', '148', '149', '150', '151', '152', '56', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '60', '176', '51', '177', '178', '179', '180', '181', '182', '183', '184', '185', '57', '186', '187', '188', '189', '190', '191', '46', '192', '193', '194', '195', '196', '197', '198', '25', '199', '200', '49', '201', '100', '202', '203', '204', '205', '206', '207', '32', '208', '209', '210']

In [93]:
from gensim.models import Word2Vec

# Train our Word2Vec model
model = Word2Vec(
    playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4
)

In [94]:
song_id = 2172

# Ask the model for songs similar to song #2172
model.wv.most_similar(positive=str(song_id))

[('3167', 0.999354362487793),
 ('10084', 0.9972447156906128),
 ('2976', 0.9966879487037659),
 ('5586', 0.9966681003570557),
 ('2704', 0.9966265559196472),
 ('3094', 0.9965333938598633),
 ('2640', 0.9962555766105652),
 ('2849', 0.9960620403289795),
 ('6685', 0.996025025844574),
 ('1922', 0.9957937598228455)]

In [95]:
print(songs_df.iloc[2172])

title     Fade To Black
artist        Metallica
Name: 2172 , dtype: object

In [96]:
import numpy as np

def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations
print_recommendations(2172)

                    title         artist
id
3167            Unchained      Van Halen
10084   Detroit Rock City           Kiss
2976         I Don't Know  Ozzy Osbourne
5586     The Last In Line            Dio
2704    Over The Mountain  Ozzy Osbourne

In [97]:
print_recommendations(2172)

                    title         artist
id
3167            Unchained      Van Halen
10084   Detroit Rock City           Kiss
2976         I Don't Know  Ozzy Osbourne
5586     The Last In Line            Dio
2704    Over The Mountain  Ozzy Osbourne

In [98]:
print_recommendations(842)

                                                    title      artist
id
413     If I Ruled The World (Imagine That) (w\/ Laury...         Nas
12335                               King Of The Dancehall  Beenie Man
330                      Hate It Or Love It (w\/ 50 Cent)    The Game
27081    Give Me Everything (w\/ Ne-Yo, Afrojack & Nayer)     Pitbull
5668                              How We Do (w\/ 50 Cent)    The Game